name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.0'
          cache: true

            # ۱. ساخت خودکار پوشه با یک شناسه (Package Name) کاملاً جدید
      - name: Create Android Platform Files
        run: flutter create . --platforms=android --org com.jetjon --project-name=app

      # ۲. اضافه کردن دسترسی اینترنت و تغییر نام نمایشی به جت‌جان
      - name: Modify AndroidManifest
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml
          sed -i 's/android:label="app"/android:label="Jetjon"/g' android/app/src/main/AndroidManifest.xml

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate App Icon
        run: dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jet-extractor-apk
          path: build/app/outputs/flutter-apk/app-release.apk
